---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: kube-ops
spec:
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: web
              protocol: TCP
          volumeMounts:
            - name: nexushome
              mountPath: /nexus-data
      volumes:
        - name: nexushome
          persistentVolumeClaim:
            claimName: nexus-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: kube-ops
  labels:
    app: nexus
spec:
  selector:
    app: nexus
  ports:
    - name: web
      port: 80
      targetPort: web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus
  namespace: kube-ops
spec:
  ingressClassName: nginx
  rules:
    - host: nexus.mr5.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexus
                port:
                  name: web
